### ISSUE TITLE
bug：表显示不完整

### ISSUE THREAD

**Issue by axlmly** [koishijs/koishi-plugin-dataview#9]
在使用随机消息插件时往里面塞入一定数量的条目后，表内只会显示一部分，且没有下一页选项按钮。使用navicat可正常显示。
![Screenshot_2023-12-28-09-03-38-899_com.android.chrome.jpg](https://github.com/koishijs/koishi-plugin-dataview/assets/41771421/70257712-67b3-4d50-b511-fdc271008a86)

**Comment by axlmly** [comment]
在pc网页端也是同样
版本：
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.16.2
    Console: 5.22.6
    Koishi Desktop: 1.0.0

**Comment by Hieuzest** [comment]
无法复现，请问：
1、使用的数据库插件是？
2、所有表均无法显示底部的分页组件还是个别表有此问题？
3、网页刷新/右上角刷新是否可解决？

**Comment by axlmly** [comment]
> 无法复现，请问：
> 1、使用的数据库插件是？
> 2、所有表均无法显示底部的分页组件还是个别表有此问题？
> 3、网页刷新/右上角刷新是否可解决？

使用的是mysql，只有randommessagedata这个表无法显示，已使用过右上角刷新，但还是一样未能解决。

**Comment by Hieuzest** [comment]
我不理解。。这个问题应该是stats没有返回该表的数据，即information_schema.tables种没有找到该表对应的行或者对应TABLE_ROWS列值为NULL，但表里既然有数据，这应该不可能发生。。？
我只能建议删掉这张表重启koishi让koishi重建一下看看了。或者也许与其他从koishi之外操作数据库的方法有关？

**Comment by axlmly** [comment]
> 我不理解。。这个问题应该是stats没有返回该表的数据，即information_schema.tables种没有找到该表对应的行或者对应TABLE_ROWS列值为NULL，但表里既然有数据，这应该不可能发生。。？ 我只能建议删掉这张表重启koishi让koishi重建一下看看了。或者也许与其他从koishi之外操作数据库的方法有关？

![ec43f4a6b907cbdf76920d9c29c52961](https://github.com/koishijs/koishi-plugin-dataview/assets/41771421/c573a321-f185-4c76-ad94-eef5aad5ece8)
重启删表重建还是同样的问题
请问这是mysql问题还是插件问题,只能扫30行

**Comment by Hieuzest** [comment]
问一下MySQL server版本，以及具体是以何种方式往表中添加这些数据的。
在删表重建后，未添加数据即表为空时，dataview是否可以正常显示？（即下方有分页组件正常显示Total 0）

我仍然只能猜测是你添加这些数据的方式导致了差异，因为其他表均无此问题，而random-send插件我也确认过没有问题，我也没有收到其他类似反馈，这应当足以表明在Koishi系统内封闭逻辑中不存在问题。
